CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar(30) NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL
);

CREATE TABLE "cart" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "total_price" float DEFAULT 0,
  "user_id" int NOT NULL
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "price" float NOT NULL,
  "available_qty" int DEFAULT 10,
  "status" bool DEFAULT true,
  "user_id" int NOT NULL
);

CREATE TABLE "productInCart" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cart_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int NOT NULL,
  "price" int NOT NULL,
  "status" bool DEFAULT true
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "total_price" int NOT NULL,
  "user_id" int NOT NULL,
  "completed" bool DEFAULT false
);

CREATE TABLE "productInOrder" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int DEFAULT 0,
  "price" float DEFAULT 0,
  "status" bool DEFAULT false
);

ALTER TABLE "product_in_order" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "product_in_order" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "product_in_cart" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");


ALTER TABLE "products" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "product_in_cart" ADD FOREIGN KEY ("cart_id") REFERENCES "cart" ("id");

ALTER TABLE "cart" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
